[package]
name = "high-speed-plotting-experiment"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
plotters = "0.3.1"
plotters-canvas = "^0.3.*"
wasm-bindgen = "0.2.78"

[profile.release]
lto = true
